# Site settings
title: Mitchell Rysavy
email: mitchell.rysavy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mrysav.github.io/" # the base hostname & protocol for your site
twitter_username: beatlefreak9
github_username:  mrysav

# Build settings
markdown: kramdown
